# Docker Compose override for Apple Silicon (ARM64) support
# Usage: docker-compose -f docker-compose.yml -f docker-compose.arm64.yml up

services:
  # Use ARM64-compatible images for Apple Silicon
  postgres:
    image: postgres:15
    platform: linux/arm64

  redis:
    image: redis:7-alpine
    platform: linux/arm64

  qdrant:
    image: qdrant/qdrant:latest
    platform: linux/arm64

  # Ollama has ARM64 support
  ollama:
    image: ollama/ollama:latest
    platform: linux/arm64
    environment:
      - OLLAMA_ORIGINS=*
      - OLLAMA_HOST=0.0.0.0
      # Disable GPU on ARM64 as it's typically not available
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_MAX_LOADED_MODELS=1

  # VSCode server with ARM64 support
  vscode:
    image: codercom/code-server:latest
    platform: linux/arm64