# Docker Compose override for macOS
# Workaround for Docker Desktop "mount options is too long" issue
# Use this file on Mac: docker-compose -f docker-compose.yml -f docker-compose.mac.yml up

services:
  vscode:
    # Use base image directly without building
    # This avoids the "mount options is too long" error on Mac
    image: codercom/code-server:latest
    build: {}  # Disable build (empty object instead of null)
    # Use ARM64 for Apple Silicon Macs
    platform: linux/arm64
    # Don't override entrypoint/command - let base image handle it
    # The workspace volume mount will make /home/coder/workspace available
    # User can open it from VSCode UI
