# Docker Compose override for macOS
# Workaround for Docker Desktop "mount options is too long" issue
# Use this file on Mac: docker-compose -f docker-compose.yml -f docker-compose.mac.yml up

services:
  vscode:
    # Build custom image with npm/node installed
    # Use DOCKER_BUILDKIT=0 to avoid BuildKit bug on Mac
    image: agentdb9-vscode:latest
    build:
      context: ./vscode
      dockerfile: Dockerfile
    # Use ARM64 for Apple Silicon Macs
    platform: linux/arm64
    # Forward common dev server ports
    ports:
      - "8080:8080"
      - "9001:9001"
      - "9002:9002"
      - "3001:3000"  # React/Next.js dev server
      - "3002:3001"  # Additional dev server
      - "5173:5173"  # Vite dev server
      - "4200:4200"  # Angular dev server
    # Override command to open workspace directory instead of current directory
    # Base image defaults to "." which causes "Workspace does not exist" error
    command: >
      --bind-addr 0.0.0.0:8080
      --auth none
      --disable-telemetry
      --disable-update-check
      --disable-workspace-trust
      --disable-file-downloads
      --disable-getting-started-override
      /home/coder/workspace
