services:
  workspace:
    image: mcr.microsoft.com/devcontainers/typescript-node:18
    volumes:
      - .:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: /workspace
    command: sleep infinity

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_WS_URL=ws://localhost:8000
      - NEXT_PUBLIC_VSCODE_URL=http://localhost:8080
      - BACKEND_URL=http://backend:8000
    volumes:
      - ./frontend:/app
      - ./shared:/shared
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - LLM_SERVICE_URL=http://llm-service:9000
      - VECTOR_DB_URL=http://qdrant:6333
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/coding_agent
      - OLLAMA_HOST=http://ollama:11434
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - COHERE_API_KEY=${COHERE_API_KEY}
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./backend:/app
      - ./shared:/shared
      - /app/node_modules
    depends_on:
      - llm-service
      - ollama
      - qdrant
      - postgres
      - redis

  llm-service:
    build:
      context: .
      dockerfile: ./llm-service/Dockerfile
    ports:
      - "9000:9000"
    environment:
      - NODE_ENV=development
      - OLLAMA_HOST=http://ollama:11434
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - HUGGINGFACE_API_KEY=${HUGGINGFACE_API_KEY}
      - MODEL_CACHE_DIR=/models/cache
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./llm-service:/app
      - ./shared:/shared
      - ./models:/models
      - /app/node_modules
    depends_on:
      - ollama
      - redis

  qdrant:
    image: qdrant/qdrant:latest
    platform: linux/amd64
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant_data
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333

  ollama:
    image: ollama/ollama:latest
    platform: linux/amd64
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    environment:
      - OLLAMA_ORIGINS=*
      - OLLAMA_HOST=0.0.0.0

  vscode:
    image: codercom/code-server:latest
    platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      - PASSWORD=${VSCODE_PASSWORD:-codeserver123}
    volumes:
      - .:/home/coder/workspace
      - ./vscode-config:/home/coder/.local/share/code-server
    command: >
      --bind-addr 0.0.0.0:8080
      --auth password
      --disable-telemetry
      /home/coder/workspace

  postgres:
    image: postgres:15
    platform: linux/amd64
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=coding_agent
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    platform: linux/amd64
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data

networks:
  default:
    name: coding-agent-network