# Docker Compose override for macOS
# Workaround for Docker Desktop "mount options is too long" issue
# Use this file on Mac: docker-compose -f docker-compose.yml -f docker-compose.mac.yml up

services:
  vscode:
    # Use base image directly without building
    # This avoids the "mount options is too long" error on Mac
    image: codercom/code-server:latest
    build: {}  # Disable build (empty object instead of null)
    # Run as root to avoid permission issues on Mac
    user: root
    environment:
      - PUID=1000
      - PGID=1000
